version: '3.8'

services:
    web:
        container_name: web
        image: nginx
        build:
            context: .
            dockerfile: .
        ports:
            - "8080:80"
        environment:
            - NGINX_HOST=foobar.com
            - NGINX_PORT=80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        privileged: true
        tty: true
        restart: always
